// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package simplebank

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          int64
	Owner       string
	Balance     int64
	Currency    string
	CreatedAt   pgtype.Timestamptz
	CountryCode pgtype.Int4
}

type Entry struct {
	ID        int64
	AccountID int64
	// Can be negative or positive.
	Amount    int64
	CreatedAt pgtype.Timestamptz
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// It must be positive.
	Amount    int64
	CreatedAt pgtype.Timestamptz
}
